<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tasksv1v2" nsURI="cs.gssi.it/tasks_v1_v2" nsPrefix="tasksv1v2">
  <eClassifiers xsi:type="ecore:EClass" name="TasksModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1"
        eType="#//tasksv1/Project" containment="true" eOpposite="#//tasksv1/Project/model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
        eType="#//tasksv1/Category" containment="true">
      <eAnnotations source="deprecated"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="done" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachments" upperBound="-1"
        eType="#//tasksv1/Attachment" containment="true">
      <eAnnotations source="deprecated"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleTask" eSuperTypes="#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeTask" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subtasks" upperBound="-1"
        eType="#//SimpleTask" containment="true"/>
  </eClassifiers>
  <eSubpackages name="tasksv1" nsURI="cs.gssi.it/tasks_v1" nsPrefix="tasksv1">
    <eClassifiers xsi:type="ecore:EClass" name="Project">
      <eAnnotations source="deprecated"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="category" lowerBound="1"
          eType="#//tasksv1/Category">
        <eAnnotations source="deprecated"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1"
          eType="#//TasksModel" eOpposite="#//TasksModel/projects"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
          eType="#//Task" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Category">
      <eAnnotations source="deprecated"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Attachment">
      <eAnnotations source="deprecated"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="externallink" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sitename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="tasksv2" nsURI="cs.gssi.it/tasks_v2" nsPrefix="tasksv2">
    <eClassifiers xsi:type="ecore:EClass" name="Project" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1"
          eType="#//TasksModel"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
          eType="#//Task" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="localattachments" upperBound="-1"
          eType="#//tasksv2/LocalAttachment" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
          eType="#//tasksv2/ExternalLink" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PersonalProject" eSuperTypes="#//tasksv2/Project"/>
    <eClassifiers xsi:type="ecore:EClass" name="SharedProject" eSuperTypes="#//tasksv2/Project"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalLink">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="externallink" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sitename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LocalAttachment">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
